/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author yepiz
 */
public class tableroGrande extends javax.swing.JFrame {

    private JLabel[] casillaJ1;
    private JLabel[] casillaJ2;
    private int posicionJ1 = 0;
    private final int casillas = 53;

    public tableroGrande() {
        initComponents();
        casillaJ1 = new JLabel[]{Lp1, Lp2, Lp3, Lp4, Lp5, Lp6, Lp7, Lp8, Lp9, Lp10, Lp11, Lp12, Lp13, Lp14, Lp15, Lp16, Lp17, Lp18, Lp19, Lp20, Lp21,
            Lp22, Lp23, Lp24, Lp25, Lp26, Lp27, Lp28, Lp29, Lp30, Lp31, Lp32, Lp33, Lp34, Lp35,Lp36,Lp37,Lp38,Lp39,Lp40,Lp41,Lp42,Lp43,Lp44,
        Lp45,Lp46,Lp47,Lp48,Lp49,Lp50,Lp51,Lp52,Lp53};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblR1 = new javax.swing.JLabel();
        lblR2 = new javax.swing.JLabel();
        lblR3 = new javax.swing.JLabel();
        lblR4 = new javax.swing.JLabel();
        lblR5 = new javax.swing.JLabel();
        lblR6 = new javax.swing.JLabel();
        lblG1 = new javax.swing.JLabel();
        lblG2 = new javax.swing.JLabel();
        lblG3 = new javax.swing.JLabel();
        lblG4 = new javax.swing.JLabel();
        lblG5 = new javax.swing.JLabel();
        lblG6 = new javax.swing.JLabel();
        lblL1 = new javax.swing.JLabel();
        lblL2 = new javax.swing.JLabel();
        lblL3 = new javax.swing.JLabel();
        lblL4 = new javax.swing.JLabel();
        lblL5 = new javax.swing.JLabel();
        lblL6 = new javax.swing.JLabel();
        lblB1 = new javax.swing.JLabel();
        lblB2 = new javax.swing.JLabel();
        lblB3 = new javax.swing.JLabel();
        lblB4 = new javax.swing.JLabel();
        lblB5 = new javax.swing.JLabel();
        lblB6 = new javax.swing.JLabel();
        Lp1 = new javax.swing.JLabel();
        Lp2 = new javax.swing.JLabel();
        Lp3 = new javax.swing.JLabel();
        Lp4 = new javax.swing.JLabel();
        Lp5 = new javax.swing.JLabel();
        Lp6 = new javax.swing.JLabel();
        Lp7 = new javax.swing.JLabel();
        Lp8 = new javax.swing.JLabel();
        Lp9 = new javax.swing.JLabel();
        Lp10 = new javax.swing.JLabel();
        Lp11 = new javax.swing.JLabel();
        Lp12 = new javax.swing.JLabel();
        Lp13 = new javax.swing.JLabel();
        Lp14 = new javax.swing.JLabel();
        Lp15 = new javax.swing.JLabel();
        Lp16 = new javax.swing.JLabel();
        Lp17 = new javax.swing.JLabel();
        Lp18 = new javax.swing.JLabel();
        Lp19 = new javax.swing.JLabel();
        Lp20 = new javax.swing.JLabel();
        Lp21 = new javax.swing.JLabel();
        Lp22 = new javax.swing.JLabel();
        Lp23 = new javax.swing.JLabel();
        Lp24 = new javax.swing.JLabel();
        Lp25 = new javax.swing.JLabel();
        Lp26 = new javax.swing.JLabel();
        Lp27 = new javax.swing.JLabel();
        Lp28 = new javax.swing.JLabel();
        Lp29 = new javax.swing.JLabel();
        Lp30 = new javax.swing.JLabel();
        Lp31 = new javax.swing.JLabel();
        Lp32 = new javax.swing.JLabel();
        Lp33 = new javax.swing.JLabel();
        Lp34 = new javax.swing.JLabel();
        Lp35 = new javax.swing.JLabel();
        Lp36 = new javax.swing.JLabel();
        Lp37 = new javax.swing.JLabel();
        Lp38 = new javax.swing.JLabel();
        Lp39 = new javax.swing.JLabel();
        Lp40 = new javax.swing.JLabel();
        Lp41 = new javax.swing.JLabel();
        Lp42 = new javax.swing.JLabel();
        Lp43 = new javax.swing.JLabel();
        Lp44 = new javax.swing.JLabel();
        Lp45 = new javax.swing.JLabel();
        Lp46 = new javax.swing.JLabel();
        Lp47 = new javax.swing.JLabel();
        Lp48 = new javax.swing.JLabel();
        Lp49 = new javax.swing.JLabel();
        Lp50 = new javax.swing.JLabel();
        Lp51 = new javax.swing.JLabel();
        Lp52 = new javax.swing.JLabel();
        Lp53 = new javax.swing.JLabel();
        Lp54 = new javax.swing.JLabel();
        Lp55 = new javax.swing.JLabel();
        Lp56 = new javax.swing.JLabel();
        Lp57 = new javax.swing.JLabel();
        Lp58 = new javax.swing.JLabel();
        Lp59 = new javax.swing.JLabel();
        Lp60 = new javax.swing.JLabel();
        Lp61 = new javax.swing.JLabel();
        Lp62 = new javax.swing.JLabel();
        Lp63 = new javax.swing.JLabel();
        Lp64 = new javax.swing.JLabel();
        Lp65 = new javax.swing.JLabel();
        Lp66 = new javax.swing.JLabel();
        Lp67 = new javax.swing.JLabel();
        Lp68 = new javax.swing.JLabel();
        lblJ1 = new javax.swing.JLabel();
        lblJ4 = new javax.swing.JLabel();
        lblJ2 = new javax.swing.JLabel();
        lblJ3 = new javax.swing.JLabel();
        btnLanzar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tablero Grande Patolli");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/azucar1.png"))); // NOI18N
        lbl1.setToolTipText("");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/azucar1.png"))); // NOI18N
        getContentPane().add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, -1, -1));

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/azucar1.png"))); // NOI18N
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/azucar1.png"))); // NOI18N
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, -1));

        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/azucar1.png"))); // NOI18N
        getContentPane().add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, -1));

        lblR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol1.png"))); // NOI18N
        getContentPane().add(lblR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        lblR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol1.png"))); // NOI18N
        getContentPane().add(lblR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        lblR3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol1.png"))); // NOI18N
        getContentPane().add(lblR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        lblR4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol1.png"))); // NOI18N
        getContentPane().add(lblR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        lblR5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol1.png"))); // NOI18N
        getContentPane().add(lblR5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        lblR6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol1.png"))); // NOI18N
        getContentPane().add(lblR6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        lblG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol4.png"))); // NOI18N
        getContentPane().add(lblG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        lblG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol4.png"))); // NOI18N
        getContentPane().add(lblG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        lblG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol4.png"))); // NOI18N
        getContentPane().add(lblG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        lblG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol4.png"))); // NOI18N
        getContentPane().add(lblG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        lblG5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol4.png"))); // NOI18N
        getContentPane().add(lblG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, -1));

        lblG6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol4.png"))); // NOI18N
        getContentPane().add(lblG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        lblL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol2.png"))); // NOI18N
        getContentPane().add(lblL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        lblL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol2.png"))); // NOI18N
        getContentPane().add(lblL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, -1, -1));

        lblL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol2.png"))); // NOI18N
        getContentPane().add(lblL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));

        lblL4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol2.png"))); // NOI18N
        getContentPane().add(lblL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        lblL5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol2.png"))); // NOI18N
        getContentPane().add(lblL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        lblL6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol2.png"))); // NOI18N
        getContentPane().add(lblL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, -1));

        lblB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol3.png"))); // NOI18N
        getContentPane().add(lblB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        lblB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol3.png"))); // NOI18N
        getContentPane().add(lblB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        lblB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol3.png"))); // NOI18N
        getContentPane().add(lblB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        lblB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol3.png"))); // NOI18N
        getContentPane().add(lblB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, -1));

        lblB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol3.png"))); // NOI18N
        getContentPane().add(lblB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        lblB6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frijol3.png"))); // NOI18N
        getContentPane().add(lblB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        Lp1.setText("Lp1");
        getContentPane().add(Lp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 40, -1));

        Lp2.setText("Lp2");
        getContentPane().add(Lp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        Lp3.setText("Lp3");
        getContentPane().add(Lp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        Lp4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp4.setForeground(new java.awt.Color(255, 255, 255));
        Lp4.setText("Lp4");
        getContentPane().add(Lp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 30, -1));

        Lp5.setText("Lp5");
        getContentPane().add(Lp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        Lp6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp6.setForeground(new java.awt.Color(255, 255, 255));
        Lp6.setText("Lp6");
        getContentPane().add(Lp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        Lp7.setText("Lp7");
        getContentPane().add(Lp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        Lp8.setText("Lp8");
        getContentPane().add(Lp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        Lp9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp9.setForeground(new java.awt.Color(255, 255, 255));
        Lp9.setText("Lp9");
        getContentPane().add(Lp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        Lp10.setText("Lp10");
        getContentPane().add(Lp10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        Lp11.setText("Lp11");
        getContentPane().add(Lp11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        Lp12.setText("Lp12");
        getContentPane().add(Lp12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        Lp13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp13.setForeground(new java.awt.Color(255, 255, 255));
        Lp13.setText("Lp13");
        getContentPane().add(Lp13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        Lp14.setText("Lp14");
        getContentPane().add(Lp14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        Lp15.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp15.setForeground(new java.awt.Color(255, 255, 255));
        Lp15.setText("Lp15");
        getContentPane().add(Lp15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        Lp16.setText("Lp16");
        getContentPane().add(Lp16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        Lp17.setText("Lp17");
        getContentPane().add(Lp17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        Lp18.setText("Lp18");
        getContentPane().add(Lp18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        Lp19.setText("Lp19");
        getContentPane().add(Lp19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        Lp20.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp20.setForeground(new java.awt.Color(255, 255, 255));
        Lp20.setText("Lp20");
        getContentPane().add(Lp20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, -1, -1));

        Lp21.setText("Lp21");
        getContentPane().add(Lp21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, -1, -1));

        Lp22.setText("Lp22");
        getContentPane().add(Lp22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, -1, -1));

        Lp23.setBackground(new java.awt.Color(255, 255, 255));
        Lp23.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp23.setForeground(new java.awt.Color(255, 255, 255));
        Lp23.setText("Lp23");
        getContentPane().add(Lp23, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, -1, -1));

        Lp24.setText("Lp24");
        getContentPane().add(Lp24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, -1, -1));

        Lp25.setText("Lp25");
        getContentPane().add(Lp25, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, -1, -1));

        Lp26.setBackground(new java.awt.Color(255, 255, 255));
        Lp26.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp26.setForeground(new java.awt.Color(255, 255, 255));
        Lp26.setText("Lp26");
        getContentPane().add(Lp26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 690, -1, -1));

        Lp27.setText("Lp27");
        getContentPane().add(Lp27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 700, -1, -1));

        Lp28.setText("Lp28");
        getContentPane().add(Lp28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 660, -1, -1));

        Lp29.setText("Lp29");
        getContentPane().add(Lp29, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, -1, -1));

        Lp30.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp30.setForeground(new java.awt.Color(255, 255, 255));
        Lp30.setText("Lp30");
        getContentPane().add(Lp30, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, -1, -1));

        Lp31.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp31.setForeground(new java.awt.Color(255, 255, 255));
        Lp31.setText("Lp31");
        getContentPane().add(Lp31, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, -1, -1));

        Lp32.setText("Lp32");
        getContentPane().add(Lp32, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, -1, -1));

        Lp33.setText("Lp33");
        getContentPane().add(Lp33, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        Lp34.setText("Lp34");
        getContentPane().add(Lp34, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        Lp35.setText("Lp35");
        getContentPane().add(Lp35, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, -1));

        Lp36.setText("Lp36");
        getContentPane().add(Lp36, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        Lp37.setBackground(new java.awt.Color(255, 255, 255));
        Lp37.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp37.setForeground(new java.awt.Color(255, 255, 255));
        Lp37.setText("Lp37");
        getContentPane().add(Lp37, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        Lp38.setText("Lp38");
        getContentPane().add(Lp38, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        Lp39.setText("Lp39");
        getContentPane().add(Lp39, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        Lp40.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp40.setForeground(new java.awt.Color(255, 255, 255));
        Lp40.setText("Lp40");
        getContentPane().add(Lp40, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        Lp41.setText("Lp41");
        getContentPane().add(Lp41, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, -1, -1));

        Lp42.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp42.setForeground(new java.awt.Color(255, 255, 255));
        Lp42.setText("Lp42");
        getContentPane().add(Lp42, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, -1, -1));

        Lp43.setText("Lp43");
        getContentPane().add(Lp43, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, -1, -1));

        Lp44.setText("Lp44");
        getContentPane().add(Lp44, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, -1, -1));

        Lp45.setText("Lp45");
        getContentPane().add(Lp45, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        Lp46.setText("Lp46");
        getContentPane().add(Lp46, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, -1));

        Lp47.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp47.setForeground(new java.awt.Color(255, 255, 255));
        Lp47.setText("Lp47");
        getContentPane().add(Lp47, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, -1));

        Lp48.setText("Lp48");
        getContentPane().add(Lp48, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, -1, -1));

        Lp49.setText("Lp49");
        getContentPane().add(Lp49, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));

        Lp50.setText("Lp50");
        getContentPane().add(Lp50, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        Lp51.setText("Lp51");
        getContentPane().add(Lp51, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        Lp52.setText("Lp452");
        getContentPane().add(Lp52, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        Lp53.setText("Lp53");
        getContentPane().add(Lp53, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        Lp54.setText("Lp54");
        getContentPane().add(Lp54, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        Lp55.setText("Lp55");
        getContentPane().add(Lp55, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        Lp56.setText("Lp56");
        getContentPane().add(Lp56, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        Lp57.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp57.setForeground(new java.awt.Color(255, 255, 255));
        Lp57.setText("Lp57");
        getContentPane().add(Lp57, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        Lp58.setText("Lp58");
        getContentPane().add(Lp58, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        Lp59.setText("Lp59");
        getContentPane().add(Lp59, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        Lp60.setText("Lp60");
        getContentPane().add(Lp60, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        Lp61.setText("Lp61");
        getContentPane().add(Lp61, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        Lp62.setText("Lp62");
        getContentPane().add(Lp62, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        Lp63.setText("Lp63");
        getContentPane().add(Lp63, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        Lp64.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Lp64.setForeground(new java.awt.Color(255, 255, 255));
        Lp64.setText("Lp64");
        getContentPane().add(Lp64, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        Lp65.setText("Lp65");
        getContentPane().add(Lp65, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        Lp66.setText("Lp66");
        getContentPane().add(Lp66, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        Lp67.setText("Lp67");
        getContentPane().add(Lp67, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        Lp68.setText("Lp68");
        getContentPane().add(Lp68, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        lblJ1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJ1.setForeground(new java.awt.Color(255, 255, 255));
        lblJ1.setText("Jugador 1");
        getContentPane().add(lblJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        lblJ4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJ4.setForeground(new java.awt.Color(255, 255, 255));
        lblJ4.setText("Jugador 4");
        getContentPane().add(lblJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, -1));

        lblJ2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJ2.setForeground(new java.awt.Color(255, 255, 255));
        lblJ2.setText("Jugador 2");
        getContentPane().add(lblJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, -1, -1));

        lblJ3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJ3.setForeground(new java.awt.Color(255, 255, 255));
        lblJ3.setText("Jugador 3");
        getContentPane().add(lblJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        btnLanzar.setText("¡Lanzar!");
        btnLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lisa.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla14.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarActionPerformed
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/imagenes/azucar1.png"));
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/imagenes/azucar2.png"));
        Random rand = new Random();

        JLabel[] labels = {lbl1, lbl2, lbl3, lbl4, lbl5};
        int puntos = 0;
        // Recorrer todos los JLabels
        for (JLabel label : labels) {
            // Generar un valor aleatorio para cada JLabel (0 o 1)
            int randomIndex = rand.nextInt(2);

            // Asignar un ícono en función del número aleatorio
            if (randomIndex == 0) {
                label.setIcon(icon1);
            } else {
                label.setIcon(icon2);
                puntos++;
            }
        }
        moverFrijol(puntos);
    }//GEN-LAST:event_btnLanzarActionPerformed

    public void moverFrijol2(JLabel lblR1, JLabel Lp) {
        int nuevaPosX = Lp.getX() + (Lp.getWidth() - lblR1.getWidth()) / 2;
        int nuevaPosY = Lp.getY() + (Lp.getHeight() - lblR1.getHeight()) / 2;
        lblR1.setLocation(nuevaPosX, nuevaPosY);
    }

    private void moverFrijol(int puntos) {
        // Verifica el número de puntos y determina el movimiento
        if (puntos == 1) {
            System.out.println("Avanzas 1 casilla");
            // Lógica para mover la ficha 1 casilla
        } else if (puntos == 2) {
            System.out.println("Avanzas 2 casillas");
            // Lógica para mover la ficha 2 casillas
        } else if (puntos == 3) {
            System.out.println("Avanzas 3 casillas");
            // Lógica para mover la ficha 3 casillas
        } else if (puntos == 4) {
            System.out.println("Avanzas 4 casillas");
            // Lógica para mover la ficha 4 casillas
        } else if (puntos == 5) {
            System.out.println("Avanzas 10 casillas");
            // Lógica para mover la ficha 10 casillas
        } else {
            System.out.println("No avanzas y cedes el turno");
            // Lógica para no mover la ficha
        }
        int posicionJ1 = obtenerPosicionActualFrijol(lblR1);
        int nuevaPosicion = posicionJ1 + puntos; // Calcular la nueva posición

        // Limitar el movimiento para no exceder el número máximo de casillas
        if (nuevaPosicion >= casillaJ1.length) {
            nuevaPosicion = casillaJ1.length - 1;  // Limitar a la última casilla si es necesario
        }

        // Obtener las coordenadas de la nueva casilla
        int x = casillaJ1[nuevaPosicion].getX();  // Coordenada X de la nueva casilla
        int y = casillaJ1[nuevaPosicion].getY();  // Coordenada Y de la nueva casilla

        moverFrijol2(lblR1, casillaJ1[nuevaPosicion]);
    }

    public int obtenerPosicionActualFrijol(JLabel lblR1) {
        for (int i = 0; i < casillaJ1.length; i++) {
            if (lblR1.getBounds().intersects(casillaJ1[i].getBounds())) {
                return i;
            }
        }
        return posicionJ1;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tableroGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tableroGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tableroGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tableroGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tableroGrande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Lp1;
    private javax.swing.JLabel Lp10;
    private javax.swing.JLabel Lp11;
    public javax.swing.JLabel Lp12;
    private javax.swing.JLabel Lp13;
    private javax.swing.JLabel Lp14;
    private javax.swing.JLabel Lp15;
    private javax.swing.JLabel Lp16;
    private javax.swing.JLabel Lp17;
    private javax.swing.JLabel Lp18;
    private javax.swing.JLabel Lp19;
    private javax.swing.JLabel Lp2;
    private javax.swing.JLabel Lp20;
    private javax.swing.JLabel Lp21;
    private javax.swing.JLabel Lp22;
    public javax.swing.JLabel Lp23;
    private javax.swing.JLabel Lp24;
    private javax.swing.JLabel Lp25;
    private javax.swing.JLabel Lp26;
    private javax.swing.JLabel Lp27;
    private javax.swing.JLabel Lp28;
    private javax.swing.JLabel Lp29;
    private javax.swing.JLabel Lp3;
    private javax.swing.JLabel Lp30;
    private javax.swing.JLabel Lp31;
    private javax.swing.JLabel Lp32;
    private javax.swing.JLabel Lp33;
    public javax.swing.JLabel Lp34;
    private javax.swing.JLabel Lp35;
    private javax.swing.JLabel Lp36;
    private javax.swing.JLabel Lp37;
    private javax.swing.JLabel Lp38;
    private javax.swing.JLabel Lp39;
    private javax.swing.JLabel Lp4;
    private javax.swing.JLabel Lp40;
    private javax.swing.JLabel Lp41;
    private javax.swing.JLabel Lp42;
    private javax.swing.JLabel Lp43;
    private javax.swing.JLabel Lp44;
    private javax.swing.JLabel Lp45;
    private javax.swing.JLabel Lp46;
    private javax.swing.JLabel Lp47;
    private javax.swing.JLabel Lp48;
    private javax.swing.JLabel Lp49;
    private javax.swing.JLabel Lp5;
    private javax.swing.JLabel Lp50;
    private javax.swing.JLabel Lp51;
    private javax.swing.JLabel Lp52;
    private javax.swing.JLabel Lp53;
    private javax.swing.JLabel Lp54;
    private javax.swing.JLabel Lp55;
    private javax.swing.JLabel Lp56;
    private javax.swing.JLabel Lp57;
    private javax.swing.JLabel Lp58;
    private javax.swing.JLabel Lp59;
    private javax.swing.JLabel Lp6;
    private javax.swing.JLabel Lp60;
    private javax.swing.JLabel Lp61;
    private javax.swing.JLabel Lp62;
    private javax.swing.JLabel Lp63;
    private javax.swing.JLabel Lp64;
    private javax.swing.JLabel Lp65;
    private javax.swing.JLabel Lp66;
    private javax.swing.JLabel Lp67;
    private javax.swing.JLabel Lp68;
    private javax.swing.JLabel Lp7;
    private javax.swing.JLabel Lp8;
    private javax.swing.JLabel Lp9;
    private javax.swing.JButton btnLanzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblB1;
    private javax.swing.JLabel lblB2;
    private javax.swing.JLabel lblB3;
    private javax.swing.JLabel lblB4;
    private javax.swing.JLabel lblB5;
    private javax.swing.JLabel lblB6;
    private javax.swing.JLabel lblG1;
    private javax.swing.JLabel lblG2;
    private javax.swing.JLabel lblG3;
    private javax.swing.JLabel lblG4;
    private javax.swing.JLabel lblG5;
    private javax.swing.JLabel lblG6;
    public javax.swing.JLabel lblJ1;
    public javax.swing.JLabel lblJ2;
    public javax.swing.JLabel lblJ3;
    public javax.swing.JLabel lblJ4;
    private javax.swing.JLabel lblL1;
    private javax.swing.JLabel lblL2;
    private javax.swing.JLabel lblL3;
    private javax.swing.JLabel lblL4;
    private javax.swing.JLabel lblL5;
    private javax.swing.JLabel lblL6;
    private javax.swing.JLabel lblR1;
    private javax.swing.JLabel lblR2;
    private javax.swing.JLabel lblR3;
    private javax.swing.JLabel lblR4;
    private javax.swing.JLabel lblR5;
    private javax.swing.JLabel lblR6;
    // End of variables declaration//GEN-END:variables
}
